set ::env(PDK) "sky130A"
set ::env(PDKPATH) "/home/furkan/.volare/sky130A"
set ::env(STD_CELL_LIBRARY) "sky130_fd_sc_hd"
set ::env(SCLPATH) "/home/furkan/.volare/sky130A/sky130_fd_sc_hd"
set ::env(DESIGN_DIR) "/openlane/designs/project5"
set ::env(//) "Basics"
set ::env(DESIGN_NAME) "top_module"
set ::env(VERILOG_FILES) "/openlane/designs/project5/src/instruction_memory.v /openlane/designs/project5/src/instruction_decoder.v /openlane/designs/project5/src/pc.v /openlane/designs/project5/src/register_file.v /openlane/designs/project5/src/top_module.v /openlane/designs/project5/src/alu.v"
set ::env(CLOCK_PERIOD) "10"
set ::env(CLOCK_PORT) "clk"
set ::env(PNR_SDC_FILE) "/openlane/designs/project5/top_module.sdc"
set ::env(SIGNOFF_SDC_FILE) "/openlane/designs/project5/top_module.sdc"
set ::env(PL_RANDOM_GLB_PLACEMENT) "1"
set ::env(FP_SIZING) "absolute"
set ::env(DIE_AREA) "0 0 300 300"
set ::env(PL_TARGET_DENSITY) "0.45"
set ::env(FP_PDN_AUTO_ADJUST) "0"
set ::env(FP_PDN_VPITCH) "25"
set ::env(FP_PDN_HPITCH) "25"
set ::env(FP_PDN_VOFFSET) "5"
set ::env(FP_PDN_HOFFSET) "5"
set ::env(DIODE_INSERTION_STRATEGY) "3"
set ::env(FP_PIN_ORDER_CFG) "/openlane/designs/project5/pin_order.cfg"
set ::env(FP_CORE_UTIL) "45"
